# Detection toggles (defaults)
DEFAULT_INTRUSION = True
DEFAULT_CROWD = True
DEFAULT_VEHICLE = False
DEFAULT_THREAT = False
DEFAULT_MOTION = False
DEFAULT_LOITER = False
DEFAULT_EMERGENCY = False
DEFAULT_FACE_RECOGNITION = True

# Camera
CAMERA_INDEX = 0

# YOLO / Detection
YOLO_MODEL_PATH = "models/yolov8n.pt"
YOLO_INFERENCE_FRAME_SKIP = 5
YOLO_MIN_CONFIDENCE = 0.35
DETECTION_CONFIRM_FRAMES = 2
DETECTION_MATCH_IOU = 0.35

# Performance
FRAME_INTERVAL_MS = 60
IDLE_FRAME_INTERVAL_MS = 60
FPS_SMOOTHING_WINDOW = 10
DISPLAY_MIRROR_FEED = True

# Motion Detection
MOTION_THRESHOLD = 25
MOTION_MIN_AREA = 1500
MOTION_DILATE_ITERATIONS = 2

# Crowd Detection
CROWD_THRESHOLD = 3

# Loitering detection
LOITER_DWELL_SECONDS = 8
LOITER_MATCH_IOU = 0.35
LOITER_TRACK_STALE_SECONDS = 2.5

# Logging
LOG_COOLDOWN = 2  # seconds
INTRUSION_EVENT_COOLDOWN_SECONDS = 20
LOCAL_LOG_FILE_PATH = "data/logs/events.log"
LOCAL_LOG_UI_MAX_ITEMS = 300
ACTIVITY_LOG_DEFAULT_COOLDOWN_SECONDS = 10
ACTIVITY_LOG_COOLDOWNS = {
    "feed:start": 2,
    "feed:pause": 2,
    "feed:stop": 2,
    "toggle": 1,
    "intrusion": 60,
    "crowd": 60,
    "vehicle": 60,
    "threat": 60,
    "motion": 30,
    "loiter": 30,
    "emergency": 5,
    "identity": 60,
    "register:sample": 2,
    "register:save": 2,
    "register:delete": 2,
    "register:duplicate": 8,
    "register:link": 4,
}

# Recording / chunk upload pipeline
RECORD_FPS = 10
RECORD_CHUNK_SECONDS = 5
FFMPEG_PATH = "./ffmpeg.exe"

# Face recognition/event dedupe (used as we add identity features)
IDENTITY_EVENT_COOLDOWN_SECONDS = 30
IDENTITY_CACHE_MAX_USERS = 100
IDENTITY_EMBEDDING_HISTORY_PER_USER = 3

# Face Registration / Recognition
FACE_DB_PATH = "data/faces/registry.json"
FACE_EMBED_SIZE = 96
FACE_MIN_SIZE = 80
FACE_DETECT_SCALE_FACTOR = 1.2
FACE_DETECT_MIN_NEIGHBORS = 5
FACE_REGISTER_SAMPLES_REQUIRED = 5
FACE_RECOGNITION_ENABLED = True
FACE_RECOGNITION_FRAME_SKIP = 4
FACE_RECOGNITION_THRESHOLD = 0.86
FACE_RECOGNITION_UNKNOWN_LABEL = "Unknown"
FACE_REGISTRATION_ALLOW_OVERWRITE = False
FACE_REGISTRATION_CASE_SENSITIVE = False
FACE_REGISTRATION_DUPLICATE_THRESHOLD = 0.86
FACE_RECOGNITION_CONFIRM_FRAMES = 2
FACE_RECOGNITION_MATCH_IOU = 0.35
FACE_PREVIEW_INTERVAL_MS = 60
FACE_PRIMARY_HOLD_FRAMES = 2
FACE_PRIMARY_MATCH_IOU = 0.30
FACE_PRIMARY_MIN_RELATIVE_AREA = 0.30

# Threat detection tuning
THREAT_CLASS_NAMES = ("knife", "scissors")
THREAT_MIN_CONFIDENCE = 0.55

# Emergency pattern
EMERGENCY_PATTERN_PATH = "data/emergency/pattern.json"
EMERGENCY_PATTERN_STEPS = 4
EMERGENCY_FINGER_NAMES = ("thumb", "index", "middle", "ring", "pinky")
EMERGENCY_HAND_LANDMARKER_MODEL_PATH = "models/hand_landmarker.task"
EMERGENCY_RESET_TIMEOUT_SECONDS = 4
EMERGENCY_HAND_MAX_NUM = 1
EMERGENCY_MIN_DETECTION_CONFIDENCE = 0.6
EMERGENCY_MIN_PRESENCE_CONFIDENCE = 0.6
EMERGENCY_MIN_TRACKING_CONFIDENCE = 0.6
EMERGENCY_FRAME_SKIP = 2

# Settings page (editable subset + stable factory defaults)
SETTINGS_EDITABLE_KEYS = (
    "CAMERA_INDEX",
    "FRAME_INTERVAL_MS",
    "IDLE_FRAME_INTERVAL_MS",
    "YOLO_INFERENCE_FRAME_SKIP",
    "YOLO_MIN_CONFIDENCE",
    "CROWD_THRESHOLD",
    "LOITER_DWELL_SECONDS",
    "THREAT_MIN_CONFIDENCE",
    "MOTION_THRESHOLD",
    "MOTION_MIN_AREA",
    "FACE_RECOGNITION_FRAME_SKIP",
    "FACE_RECOGNITION_THRESHOLD",
    "FACE_REGISTER_SAMPLES_REQUIRED",
    "EMERGENCY_RESET_TIMEOUT_SECONDS",
)

SETTINGS_FACTORY_DEFAULTS = {
    "CAMERA_INDEX": 0,
    "FRAME_INTERVAL_MS": 60,
    "IDLE_FRAME_INTERVAL_MS": 60,
    "YOLO_INFERENCE_FRAME_SKIP": 5,
    "YOLO_MIN_CONFIDENCE": 0.35,
    "CROWD_THRESHOLD": 3,
    "LOITER_DWELL_SECONDS": 8,
    "THREAT_MIN_CONFIDENCE": 0.55,
    "MOTION_THRESHOLD": 25,
    "MOTION_MIN_AREA": 1500,
    "FACE_RECOGNITION_FRAME_SKIP": 4,
    "FACE_RECOGNITION_THRESHOLD": 0.86,
    "FACE_REGISTER_SAMPLES_REQUIRED": 5,
    "EMERGENCY_RESET_TIMEOUT_SECONDS": 8,
}
